### ISSUE TITLE
Potential additional "prior work" citation (not Lisp, rather JS)?

### ISSUE THREAD

**Issue by kyanha** [kennytilton/cells#10]
The closest I can come to Cells in what I've worked with prior to this is Facebook's ReactJS, but it's fairly limited to client-side display propagation of changes triggered either by client action or server updates.

I don't know if this really meshes with your criteria for prior work, but I hope it's useful.

**Comment by kennytilton** [comment]
Well, ReactJS has "react" in their name, but they only simulate reactivity by re-running view functions under select circumstances. They do have the declarative win that way, but as they say, state management is still up to us. After a few years they even explicitly rejected the reactive paradigm because, in their words, React wants to control when things get re-rendered.
